{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Release.Name }}
spec:
  controller: k8s.io/ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-weba
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 | trimSuffix "\n" }}
spec:
  ingressClassName: {{ .Release.Name }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /admin
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Release.Name }}-weba
                port:
                  number: 8010

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webu
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 | trimSuffix "\n" }}
spec:
  ingressClassName: {{ .Release.Name }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Release.Name }}-webu
                port:
                  number: 80
{{- end }}
