apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-weba
  labels:
{{ toYaml .Values.service.labels | indent 4 | trimSuffix "\n" }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: communigate
  ports:
    - name: httpa
      protocol: TCP
      port: 8010
      targetPort: 8010
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webu
  labels:
{{ toYaml .Values.service.labels | indent 4 | trimSuffix "\n" }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: communigate
  ports:
    - name: httpu
      protocol: TCP
      port: 80
      targetPort: 80
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
