apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: communigate
spec:
  replicas: {{ .Values.communigate.replicaCount }}
  selector:
    matchLabels:
      app: communigate
  template:
    metadata:
      labels:
        app: communigate
    spec:
      containers:
        - name: communigate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{ if .Values.persistence.enabled }}
          volumeMounts:
          - name: storage
            mountPath: "/var/CommuniGate"
          {{ end }}
          ports:
            - containerPort: 9010
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  {{ if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{ end }}



